language: go
go:
  - '1.x'

install:
  - make tools
  - pip install --user --upgrade sphinx semantic-version requests urllib3[secure]

script:
  - make dist
  - ./build/coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  apt:
    packages:
    - latexmk
    - texlive-binaries
    - texlive-fonts-recommended
    - texlive-latex-base
    - texlive-latex-extra
    - texlive-latex-recommended
