language: go
go:
  - 1.x

sudo: required

services:
  - docker

env:
  global:
    - secure: iyv/cQh7z/PjRyEySKELsd3L69AdRVlCnZrtozvM/Z+poeSnGtQIRLWgOw/Pe5ueNa/v7Wq2BKw1DHeTrgSnvNNt/uoTUWLY5UcHkPHQYm67DeB7CffSELgr8l6K7eBOqTn2Hu6mzPlmU6l3v8CBHg8uSJT6wv/XKqn2Ut74OBA7wCYRQyEXcnr26C7ytnN/XaaR/RPzXYyxoB6/l6aH1/PK9rt+btdBu4TPo5zZm6KVA8pp85KG7xfGjq6kNG+kDwFiaj6/DJmnxYKxsiyv/AsEtLmElxGKQQqCnOefbNwqSsdYDDqy5AikZ+ZfJQLRrLJzcHDzgREaiPCF0QVfGttcuX5AXpPkrBlKeixku91Dir4hebYAN7SWWwKktu8hqKTtQjc8eJMEbQVKTtk3yeRKqC4I8lUK6TBrJA7tnQpgq8w67Vm81P18UPPjKm6Wf6aCJEKSvrnVSwLvIrEN8q/ybrCupvvcze0l9nsQhJG/79BQX31mjZkqT9MdskgYgD3wrB2LexLYkw4BeyKOV1/fTyz7q82ocfEdNMHTnPKD4B2bXtl1Alx8wluIFjwOvy8QZ9Hopz+cNnfN/dOJcQn7hPQbjqIP7uumUTP2vVk3mtwPDKLYqfCeO1ZLwHClXog6Q2k8gb6mkEfVx6ygq/JxM5LkSnTdfyowLLTp7W0=
    - secure: gXwZlcsYZtbp4P/xABkXeBRHawfoUoBosS65s2fahC7xXJB3JPNsDNvvKMPz2sT4UIQ7bwsu2fJIUG3mFH2YjxvZsdKiQwNe+ghj+YpGPL6HPe08ZuxR+E84khK8zoSBtb80NdhxJvYVRJm0IaZK2dQx+BUtsSRTHNR859EdOL/MdVc0fgBRluar4jfq1MlVZH26AYZlZIdD40ZUmJXI18dsG+YSEXB+W4re5bpz5C++qdC3EiCghOPG1SOQRnMTG+6iyb3sWlyUlDfOa20uf3NPWc/pQCPRsKITenWuxd86DRYvhoknzGM4oxUtNymHv7n3fNZ/K49WDMzAhEd/kfNjOMc+CpLWtugqnSPpYIjKzDA8rMuvaIWjjgNcg6u5DV3uxohyJw/bIv23BB7i4b9C5mifymFMhkRqK01JbCMjIxRgzBspf3v3wvZrFntt2M/ic3A8BLxRLnaz76eKANlPejwhKkbvAYHqZQKQEywRyV6iKlfQjB2sbSty8bJW/vxXbigjFydIT4Af2CLzhU2XyT1vMXw8HPV1bKqJW1acpxlVDHrINcmKRhA//zEg0Z7a0fBlhmK/m5e7omrMDxxKFGDkDyKNy90WQZ+vh5Cxi2TWMs113ug/R91svAmAhUnUZV6dwx7dfxTbXVdiSxGnNbunNHNr4Pnbvdogyhk=

install:
  - make tools
  - pip install --user --upgrade sphinx semantic-version requests urllib3[secure]

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64  > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - "./cc-test-reporter before-build"

script:
  # Go1.10 is required to have proper use of coverprofile for multiple packages
  - TESTARGS="-coverprofile coverage.txt" make dist
  - cp coverage.txt c.out
  - ./docker_build.sh

after_script:
  - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: script
    script: bash deploy.sh
    on:
      all_branches: true
    skip_cleanup: true

  - provider: releases
    overwrite: true
    api_key:
      secure: ZHIdTaOa3MbxENL2spVhKk3P3DatNXZ5hjg+4oe0hCdZsr1feb0WnC4jsfMeU5rQcaiwJEWknrvdq66RUQvbcOtEr/SIrPUplc/qjWiH6i81lELX1OVp41M1YSkjEKnjCUqyW1lcBCS8KgwaiNCRd6BI6BbPhNy4bO0ssQXnT8wuaWaPExgjo8qck9qsB7n+Ta0gwkHd9Ly3FdH1I4DmcwB1T0kB9MRjmJk5WeX8uBN7vJjcrsy8VbDwLxTRhjAbLSz7Pa7fUBtA4ssXJQbbAxpXaaa8FkkBPLXCf+zsq6+Cqnhj/Y8O360iu92A6hgNKUkCCNqXJHxYP6L6ETY/wh+6XlnWKWPSCy3/z5KFJYptVDD70EStKhHj3Gwjyh0mXGGt4UpgMBZlTzj2I0uReS6BCGcJ3t0/ny3L0x4LhnQpNGsgzm/2CiLfr0PUcBgAI4b6jUpzfZlG9H7DfiwHJdhU1yTbelBjf4nYEAG2oQVijD9wSiMyTShWt6Hh4Vw1WsGemd14TzOdDP6eAbECqjAb6OIpe8edeiD/fdwXoXFCdmMHuq19XXGloCOgJpfExxByagZhN8SsFxsr5mUdnSSuXUZ3XtcoRhCum7J7ZsTIJ6nhS6DrvVjI9Hwiq2d3IK10JgQ6K48C/c0qW+TvOUJvgmeQCHpSF+gLJWQlodY=
    file:
      - dist/yorc.tgz
      - dist/yorc-server-*-distrib.zip
    skip_cleanup: true
    on:
      tags: true

addons:
  apt:
    packages:
    - latexmk
    - texlive-binaries
    - texlive-fonts-recommended
    - texlive-latex-base
    - texlive-latex-extra
    - texlive-latex-recommended