language: go
go:
  - '1.x'

install:
  - make tools
  - pip install --user sphinx semantic-version requests

script:
  - make dist
  - ./build/coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  apt:
    packages:
    - latexmk
    