apiVersion: v1
clusters:
- cluster:
    server: http://localhost:8050
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    namespace: default
  name: default-context
current-context: default-context
kind: Config
preferences: {}
users: []